[build]
builder = "nixpacks"
buildCommand = "echo 'No build step required for server'"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[nixpacks]
nodejs = { version = "18" }

[nixpacks.plan.setup]
nixPkgs = ["nodejs_18"]

[nixpacks.plan.install]
cmds = ["npm install --production"]

[nixpacks.plan.build]
cmds = ["echo 'No build step required for server'"]

[nixpacks.plan.start]
cmd = "node server.js"
